first attempt
A-Ih/first-term pull request #2
Opened 2020-07-06 14:23 UTC by A-Ih

2020-07-06 23:18 UTC, kt-cpp commented on asm/mul.asm
> +        lea             rdi, [rdi - 128 * 8]
Не используется rcx

2020-07-06 23:18 UTC, kt-cpp commented on asm/mul.asm
> +        lea             rdi, [rdi - 128 * 8]
И везде в этой функции, где 128

2020-07-06 23:18 UTC, kt-cpp commented on asm/mul.asm
> +        sub             rsp, rcx
Может все-таки через `lea` стек подвинем?

2020-07-06 23:19 UTC, kt-cpp commented on asm/mul.asm
> +;  carry  -- r14
Коммент поехал

2020-07-06 23:32 UTC, kt-cpp commented on asm/mul.asm
> +            .no_carry:
Нарисуй, пожалуйста, картинку про это. Меня особенно интересует, что будет, когда последний разряд одного числа умножится на другое число.

2020-07-06 23:33 UTC, kt-cpp requested changes
В целом хорошо, лайк за комменты

2020-09-05 08:49 UTC, A-Ih commented on asm/mul.asm
> +;  carry  -- r14
fixed

2020-09-05 08:50 UTC, A-Ih commented on asm/mul.asm
> +        sub             rsp, rcx
fixed

2020-09-05 08:50 UTC, A-Ih commented on asm/mul.asm
> +        lea             rdi, [rdi - 128 * 8]
fixed

2020-09-05 08:50 UTC, A-Ih commented on asm/mul.asm
> +            .no_carry:
![explanation](https://user-images.githubusercontent.com/35338443/92301650-0191e100-ef6e-11ea-9161-f45655fb0a9b.jpg)

2020-09-23 22:40 UTC, kt-cpp approved these changes
OK

2020-09-23 22:40 UTC, merged