first attempt (vector)
A-Ih/first-term pull request #3
Opened 2020-07-07 12:58 UTC by A-Ih

без обработки ошибок выходит < 300 строк

2020-07-08 10:33 UTC, sorokin commented
@A-Ih Если запускать с санитайзерами, то программа выдаёт такую ошибку:
```
[ RUN      ] correctness.default_ctor
/home/ivan/d/cpp-year2019/ibragim-akhmad/first-term/vector/vector.h:119:38: runtime error: pointer index expression with base 0x000000000000 overflowed to 0xfffffffffffffff
```

@kt-cpp Лев, ты не знаешь почему автоматические тесты это не поймали?

2020-07-08 10:55 UTC, kt-cpp commented
@sorokin скорее всего не хватило каких флагов санитайзеров. Локальные флаги запуска совпадают с теми, что СMakeLists?

2020-07-09 19:17 UTC, sorokin commented
@A-Ih

```
template<typename T>
const T& vector<T>::operator[](size_t i) const {
  error(i >= size_, std::to_string(i), INVALID_INDEX);
  return data_[i];
}
```

Очень дорогой operator[] получается. Вы же понимаете, что у вас `error` это обычная функция и чтобы её вызвать нужно вычислить все её параметры -- в частности `std::to_string(i)`. Я считаю, что это не хорошо на каждый `operator[]` делать `std::to_string`. Хорошо было бы сделать, чтобы `std::to_string(i)` вычислялось только если условие `i >= size_` выполнилось.

2020-07-09 19:23 UTC, sorokin commented
```
  throw std::runtime_error(ERRS[err_code]
                           + message
                           + " in vector " + ptr_to_str(this)
                           + " [size = " + std::to_string(size_) + "]");
```

Идиоматический способ делать такие вещи это использовать `std::stringstream`. Тогда вам было бы не нужно вызывать тут `std::to_string` и `ptr_to_str`.

2020-07-09 19:33 UTC, sorokin commented
```
template<typename T>
typename vector<T>::iterator vector<T>::insert(vector<T>::iterator pos, const T &val) {
  if (pos < begin() || pos > end()) {
```

Такое сравнение может не всегда работать. Дело в том, что сравнение на меньше указателей из разных объектов в памяти это undefined behavior. В вашем случае скорее всего будет работать, но для встроенныго массива, компиляторы могут просто удалять такую проверку. Поэтому здесь тоже опасно.

Чтобы исравить можно написть как здесь: https://devblogs.microsoft.com/oldnewthing/20170927-00/?p=97095

2020-07-09 19:36 UTC, sorokin commented
```
template<typename T>
template<typename U>
std::string vector<T>::ptr_to_str(U *ptr) {
  std::ostringstream conv;
  conv << ptr;
  return conv.str();
}

template<typename T>
template<typename U>
std::string vector<T>::ptr_to_str(const U *ptr) {
  return ptr_to_str(const_cast<U*>(ptr));
}
```

Я вы советовал реализовать неконстантную через константную, а не наоборот. Тогда вам бы был не нужен const_cast.

2020-07-09 19:38 UTC, sorokin commented
```
  static const size_t INVALID_INDEX = 1;
  static const size_t INVALID_IT = 2;
  static const size_t INVALID_IT_RANGE = 3;

  int err_code
```

Почему в одном месте они size_t, а в другом int? И ещё, почему это не enum?

2020-07-10 08:09 UTC, A-Ih commented
Я решил избавиться от проверок указателей.
Единственный каст, который работал с `uintptr_t` (`reinterpret_cast`), не решает проблему (насколько я понял, пример из статьи сломает такую реализацию).

2020-07-10 12:12 UTC, kt-cpp requested changes

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +    typedef const T* const_iterator;
[note] `using`

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +  static std::ostringstream conv;
Зачем тут статик? Если эту функцию вызовут несколько раз, то второй раз выведется первое тоже

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +  for (size_t i = len; i --> 0;) {
[minor] Пожалуйста замени этот шизоператор на читаемый код

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +    start[i].~T();
У итератора нет квадратный скобок

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +void vector<T>::destroy_elems(iterator start, size_t len) const {
[minor] Какие есть причины у этой функции быть не статической?

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +void vector<T>::delete_buffer(T *buff, size_t len) const {
[minor] Какие есть причины у этой функции быть не статической?

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +  check_index(i);
Не вижу причин замедлять оператор [], который декларирует ub в случае неправильного индекса. Если хочешь иметь какие-то проверки, сделай так, чтобы они работали только в дебажной сборке, например с помощью асёрторв

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +  check_index(i);
Не вижу причин замедлять оператор [], который декларирует ub в случае неправильного индекса. Если хочешь иметь какие-то проверки, сделай так, чтобы они работали только в дебажной сборке, например с помощью асёрторв

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +  check_empty();
Не вижу причин замедлять функцию, которая декларирует ub в случае пустого. Если хочешь иметь какие-то проверки, сделай так, чтобы они работали только в дебажной сборке, например с помощью ассёртов

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +  check_empty();
Не вижу причин замедлять функцию, которая декларирует ub в случае пустого. Если хочешь иметь какие-то проверки, сделай так, чтобы они работали только в дебажной сборке, например с помощью ассёртов

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +  check_empty();
Не вижу причин замедлять функцию, которая декларирует ub в случае пустого. Если хочешь иметь какие-то проверки, сделай так, чтобы они работали только в дебажной сборке, например с помощью ассёртов

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +  check_empty();
Не вижу причин замедлять функцию, которая декларирует ub в случае пустого. Если хочешь иметь какие-то проверки, сделай так, чтобы они работали только в дебажной сборке, например с помощью ассёртов

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +  check_empty();
Не вижу причин замедлять функцию, которая декларирует ub в случае пустого. Если хочешь иметь какие-то проверки, сделай так, чтобы они работали только в дебажной сборке, например с помощью ассёртов

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +  T tempval = val;
Эту копи можно не делать в отсустствии переаллокаций

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +  return insert(const_cast<iterator>(pos), val);
Расскажи почему этот и подобные ниже касты валидны

2020-07-10 12:12 UTC, kt-cpp commented on vector/vector.h
> +    *i = *(i + diff);
Лишние копирования

2020-07-10 14:20 UTC, A-Ih commented on vector/vector.h
> +void vector<T>::destroy_elems(iterator start, size_t len) const {
Цепочка вызовов из конструктора копирования содержит эту функцию

2020-07-10 14:25 UTC, kt-cpp commented on vector/vector.h
> +  erase(end() - 1);
Слишком много кода для такой функции

2020-07-10 14:31 UTC, kt-cpp commented on vector/vector.h
> +void vector<T>::destroy_elems(iterator start, size_t len) const {
И?

2020-07-10 14:31 UTC, kt-cpp commented on vector/vector.h
> +  return insert(const_cast<iterator>(pos), val);
Так и не рассказал

2020-07-10 14:35 UTC, kt-cpp commented on vector/vector.h
> +  size_++;
Напиши нормальный `push_back` и переиспользуй здесь

2020-07-10 14:35 UTC, kt-cpp commented on vector/vector.h
> +}
Почитай про ADL/Koening lookup и подумай

2020-07-10 14:36 UTC, kt-cpp requested changes
1. Так и не научился отвечать на комментарии
2. Убери `assert`, так как проще декларировать UB в случае не подходящего состояния вектора. Ассерты нужны для проверки собственных инвариантов.
3. Остальные фиксы

2020-09-05 12:09 UTC, A-Ih commented on vector/vector.h
> +  erase(end() - 1);
fixed

2020-09-05 12:09 UTC, A-Ih commented on vector/vector.h
> +  size_++;
fixed

2020-09-05 12:10 UTC, A-Ih commented on vector/vector.h
> +}
fixed

2020-09-13 12:00 UTC, A-Ih commented on vector/vector.h
> +void vector<T>::destroy_elems(iterator start, size_t len) const {
fixed

2020-09-15 16:14 UTC, A-Ih commented on vector/vector.h
> +void vector<T>::delete_buffer(T *buff, size_t len) const {
fixed

2020-09-21 18:36 UTC, kt-cpp requested changes

2020-09-21 18:36 UTC, kt-cpp commented on vector/vector.h
> +}
[minor] Сюда бы ассёрт на то, что новая вместимость не меньше старого размера, иначе цикл на 85 строке вообще говоря полезет в невалидную память

2020-09-21 18:36 UTC, kt-cpp commented on vector/vector.h
> +  }
[minor] А чего не перевызвать `ensure_capacity`

2020-09-22 18:43 UTC, A-Ih commented on vector/vector.h
> +  }
fixed

2020-09-22 18:43 UTC, A-Ih commented on vector/vector.h
> +}
fixed

2020-09-30 21:12 UTC, kt-cpp approved these changes

2020-09-30 21:12 UTC, merged