first try bigint-opt
A-Ih/first-term pull request #4
Opened 2020-07-09 17:18 UTC by A-Ih

2020-07-10 14:55 UTC, kt-cpp requested changes
* Из-за произвольного Т куча проблем с исключениями
* Обращениями к памяти, которая не является валидным объектом
* Слишком много уровней индерекции
Рекомендуется не пытаться загнать дз без его понимания в последний день

2020-09-22 20:32 UTC, kt-cpp requested changes

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/cow_storage.h
> +  std::shared_ptr< std::vector<T> > >::type common_buff;
* [minor] Лучше сделать подобные проверки через `static_assert` для повышения читаемости
* Выбрано слишком строгое ограничение, ибо нет причин не иметь данный класс для `float *` или даже любого `U *` в целом

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/cow_storage.h
> +}
Почему бы просто не воспользоваться оператором присваивания у shared_ptr?

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/cow_storage.h
> +}
Кажется в нормальном мире у тебя не должно быть такой функции, ибо объекты со счётчиком ссылок в 0 просто не должны существовать

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/cow_storage.h
> +  return *(common_buff.get());
[minor] У shared_ptr уже перегружен `opeator *` правильным образом

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/cow_storage.h
> +  return *(common_buff.get());
На 63 строке подобное

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/cow_storage.h
> +    common_buff.reset(new std::vector<T>(*common_buff));
Понимаешь ли ты, что произойдёт, если `reset` кинет исключение?

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/cow_storage.h
> +struct cow_storage {
[style] В целом нет особых причин в шаблонных классах разносить объявление и определение функции

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/small_obj_storage.h
> +  static const size_t SMALL_OBJECT_SIZE = sizeof(cow_storage<T>*) / sizeof(T) + 1;
* [note] Респект за `+ 1`
* [minor] `constexpr` чтобы это гарантированно было константой компиляции
* [minor] Какая причина этой константе быть публичной?

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/small_obj_storage.h
> +    cow_storage<T> *dynamic_storage;
Указатель на `shared_ptr` это уже слишком много уровней ~~иронии~~ индирекции. Можно уменьшить как минимум на 1

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/small_obj_storage.h
> +  } else {
Почему бы тут сразу не написать в память под маленький буффербез лишнего вызова `resize`?

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/small_obj_storage.h
> +  swap(this->small_obj_buff, temp.small_obj_buff);
[minor] Не обязательно обращаться через `this` явно

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/small_obj_storage.h
> +  void push_back(const T &val);
Почему у тебя в одном месте ссылка а в другом значение?

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/small_obj_storage.h
> +  void resize(size_t new_sz, T fill_value);
[minor] Вместо двух перегрузок можно сделать просто дефольный аргумент у функции

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/cow_storage.h
> +}
Я посмотрел на его использование, с одной стороны код становится короче, но с другой, изменив всего пару мест можно убрать лишнею проверку из читающих операций

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/small_obj_storage.h
> +      small_obj_buff.static_storage.len = new_sz;
Кажется тут забыли вызвать деструкторы в случае уменьшения размера

2020-09-22 20:32 UTC, kt-cpp commented on bigint-optimized/small_obj_storage.h
> +  dynamic_storage->get_storage() = new_buffer;
У вектора есть конструктор от двух итераторов на такой случай, чтобы не делать кучу лишних копирований. Можно его аккуратно прокинуть в cow_storage и будет минимально возможное число копий и аллокаций

2020-09-27 13:24 UTC, A-Ih commented on bigint-optimized/cow_storage.h
> +  std::shared_ptr< std::vector<T> > >::type common_buff;
fixed: поменял на `static_assert` и расширил ограничение до `is_trivial`

2020-09-27 13:24 UTC, A-Ih commented on bigint-optimized/cow_storage.h
> +}
fixed: убрал `shared_ptr`

2020-09-27 13:24 UTC, A-Ih commented on bigint-optimized/cow_storage.h
> +}
fixed: убрал `shared_ptr`

2020-09-27 13:24 UTC, A-Ih commented on bigint-optimized/cow_storage.h
> +  return *(common_buff.get());
fixed

2020-09-27 13:24 UTC, A-Ih commented on bigint-optimized/cow_storage.h
> +    common_buff.reset(new std::vector<T>(*common_buff));
fixed

2020-09-27 13:24 UTC, A-Ih commented on bigint-optimized/cow_storage.h
> +struct cow_storage {
fixed: в `cow_storage.h` определил функции на месте, в `small_obj_storage.h` оставил как есть, чтобы лучше было видно интерфейс класса

2020-09-27 13:24 UTC, A-Ih commented on bigint-optimized/small_obj_storage.h
> +  static const size_t SMALL_OBJECT_SIZE = sizeof(cow_storage<T>*) / sizeof(T) + 1;
fixed

2020-09-27 13:24 UTC, A-Ih commented on bigint-optimized/small_obj_storage.h
> +    cow_storage<T> *dynamic_storage;
fixed: избавился от `shared_ptr`

2020-09-27 13:24 UTC, A-Ih commented on bigint-optimized/small_obj_storage.h
> +  } else {
fixed

2020-09-27 13:24 UTC, A-Ih commented on bigint-optimized/small_obj_storage.h
> +  swap(this->small_obj_buff, temp.small_obj_buff);
fixed

2020-09-27 13:24 UTC, A-Ih commented on bigint-optimized/small_obj_storage.h
> +  void push_back(const T &val);
fixed

2020-09-27 13:24 UTC, A-Ih commented on bigint-optimized/small_obj_storage.h
> +  void resize(size_t new_sz, T fill_value);
fixed

2020-09-27 13:24 UTC, A-Ih commented on bigint-optimized/small_obj_storage.h
> +      small_obj_buff.static_storage.len = new_sz;
fixed: теперь `T` тривиален и его деструктор можно не вызывать

2020-09-27 13:24 UTC, A-Ih commented on bigint-optimized/small_obj_storage.h
> +  dynamic_storage->get_storage() = new_buffer;
fixed

2020-09-30 21:47 UTC, kt-cpp commented on bigint-optimized/small_obj_storage.h
> +      small_obj_buff.static_storage.len = new_sz;
Тебе не хватает тут ещё одного [условия](https://en.cppreference.com/w/cpp/types/is_destructible) в таком случае

2020-09-30 21:55 UTC, kt-cpp requested changes
Почти готово

2020-10-02 07:32 UTC, A-Ih commented on bigint-optimized/small_obj_storage.h
> +      small_obj_buff.static_storage.len = new_sz;
fixed

2020-10-02 09:49 UTC, kt-cpp approved these changes

2020-10-02 09:52 UTC, merged